textclassification/classification/urls.py
from django.urls import path

from . import views

app_name = 'classification'
urlpatterns = [
    path('',views.index, name='index'),
    path('ajax_posting', views.ajax_posting, name='ajax-posting')
]

textclassification/hello/urls.py
from django.urls import path
from hello import views

urlpatterns = [
    path("", views.home, name="home"),
]

textclassification/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('owner', views.owner, name='owner'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

textclassification/textclassification/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('classification/', include('classification.urls')),
    path('admin/', admin.site.urls),
]

textclassification/classification/models.py
from django.db import models

# Create your models here.

textclassification/polls/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

textclassification/classification/forms.py
from django import forms

class NameForm(forms.Form):
    text_to_classify = forms.CharField(widget=forms.Textarea,label='Text to Classify', max_length=1000)

textclassification/classification/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect,JsonResponse
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.urls import reverse
from django.views import generic
from .forms import NameForm
from .huggingface import HuggingFace

def index(request):
    # return HttpResponse("Hello, world. You're at the polls index.")
    form = NameForm()
    context = {"form": form}
    return render(request, "classification/index.html", context=context)


def ajax_posting(request):
    if(request.headers.get('x-requested-with') == 'XMLHttpRequest'):
        inp = request.POST['text_to_classify']
        result = HuggingFace().query(inp)
        #return HttpResponse(F'result of <b>{inp}</b> is <br/>{str(result)}')
        return JsonResponse(result)
    return HttpResponseNotFound("hello")  

textclassification/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
    return HttpResponse("Hello, Django!")

textclassification/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.urls import reverse
from django.views import generic

from .models import Choice, Question

def owner(request):
    return HttpResponse("Hello, world. 9ead219c is the polls index.")

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    
def sentimentAnalysis(request):
    render(request, "polls/sentimentAnalysis.html")

textclassification/classification/templates/classification/base.html
{% extends "classification/bootstrap.html" %}
{% load bootstrap5 %}
{% block bootstrap5_content %}
    <div class="container">
        <h1>
            {% block title %}
                (no title)
            {% endblock title %}
        </h1>
        <p>
            {% comment %} <a href="{% url 'index' %}">home</a> {% endcomment %}
            {% comment %} <a href="{% url 'formset_default' %}">formset</a>
            <a href="{% url 'form_default' %}">form</a>
            <a href="{% url 'form_by_field' %}">form_by_field</a>
            <a href="{% url 'form_horizontal' %}">form_horizontal</a>
            <a href="{% url 'form_inline' %}">form_inline</a>
            <a href="{% url 'form_with_files' %}">form_with_files</a>
            <a href="{% url 'pagination' %}">pagination</a>
            <a href="{% url 'misc' %}">miscellaneous</a> {% endcomment %}
        </p>
        {% autoescape off %}
            {% bootstrap_messages %}
        {% endautoescape %}
        {% block content %}
            (no content)
        {% endblock content %}
    </div>
{% endblock bootstrap5_content %}

textclassification/classification/templates/classification/bootstrap.html
{% extends "bootstrap5/bootstrap5.html" %}
{% block bootstrap5_head %}
    {% block head %}
    {% endblock head %}
    {% block bootstrap5_title %}
        {% block title %}
        {% endblock title %}
    {% endblock bootstrap5_title %}
{% endblock bootstrap5_head %}

textclassification/classification/templates/classification/index.html
{% extends "classification/base.html" %}
{% load bootstrap5 %}
{% block title %}
    Text Classification using Huggingface APIs
{% endblock title %}
{% block head %}
{% endblock head %}
{% block content %}
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
    <script>
        $(function(){
            console.log( "ready!" );
            $('#submitButton').click(function(e){
                console.log('submitting');
                e.preventDefault();
                $('#result').html("<h3>Loading...</h3>") 
                $.ajax({
                    type : "POST", 
                    url: "{% url 'classification:ajax-posting' %}",
                    //url: "ajax_posting",
                    data: {
                        text_to_classify : $('#id_text_to_classify').val(),
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        dataType: "json",
                    },
                    success: function(data){
                        console.log(data)
                        //console.log(data['all_data'].length)
                        html = ""
                        for(i=0; i<data['all_data'].length;i++){
                            //console.log(data['all_data'][i])
                            for(j=0; j<data['all_data'][i].length;j++){
                                if(j==0){
                                    html+='<h4>model: '+data['all_data'][i][j]['model']+'</h4>'
                                }else{
                                    html+=data['all_data'][i][j]['label'] + ': '
                                    +(data['all_data'][i][j]['score']*100).toFixed(2)+'%<br/>'
                                    //console.log(data['all_data'][i][j]['label'])
                                    //console.log(data['all_data'][i][j]['score'])
                                }
                            }
                            html += "<br/><br/>"

                        }
                        console.log(html)
                        $('#result').html(html) 
                    },
                
                    failure: function() {
                        console.log('failure')
                    }
                });
            }); 
        });

    </script>
    {% comment %} This is <em> bootstrap5</em > for <strong>Django</strong>. {% endcomment %}
    <div class="row">
        <div class="col-md-6">
            <form id="form" class="form" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input id="submitButton"
                       class="btn btn-primary"
                       type="submit"
                       value="Submit"/>
            </form>
        </div>
        <div class="col-md-6" id="result">that here</div>
    </div >
{% endblock content %}

textclassification/polls/templates/polls/detail.html
{# Load the tag library #}
{% load bootstrap5 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<form role='form' action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% comment %} {% bootstrap_form form %} {% endcomment %}
    <fieldset>
        <legend>
            <h1>{{ question.question_text }}</h1>
        </legend>
        {% if error_message %}
            <p>
                <strong>{{ error_message }}</strong>
            </p>
        {% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio"
                   name="choice"
                   id="choice{{ forloop.counter }}"
                   value="{{ choice.id }}"/>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
            <br/>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote"/>
</form>

textclassification/polls/templates/polls/index.html
{% load static %}
{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}"/>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

textclassification/polls/templates/polls/results.html
{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>